import { readFileSync as cat, writeFileSync as echo } from "fs";
import path from "path";

const rootDir = path.join(import.meta.dirname, "..");

const pkgJsonPath = path.join(rootDir, "package.json");

const pkgJson = JSON.parse(cat(pkgJsonPath, { encoding: "utf-8" }));

const environment = {
    version: pkgJson["version"] ?? "0.0.1",
    production: true,
    apiUrl: process.env.API_URL ?? ""
};

const content = `// Auto-generated by ${import.meta.filename} from environment variables.
export const environment = ${JSON.stringify(environment, null, 4)};
`

const target = path.join(rootDir, "src", "environments", "environment.prod.ts");


echo(target, content);
console.log("Generated %s", target);
