import { writeFileSync as echo } from "fs";
import path from "path";

const environment = {
    production: true,
    apiUrl: process.env.API_URL ?? ""
};

const content = `// Auto-generated by ${import.meta.filename} from environment variables.
export const environment = ${JSON.stringify(environment, null, 4)};
`

const target = path.join(import.meta.dirname, "..", "src", "environments", "environment.prod.ts");

echo(target, content);
console.log("Generated %s", target);
